### ISSUE TITLE
Global Suppressions

### ISSUE THREAD

**Issue by agray** [StyleCop/StyleCop#103]
It appears that currently the latest released version does not yet support Global Suppressions.

I would like to be able to specify a Suppressions.cs file once in my project and not have to replicate these contents at the top of every .cs file.

    using System.Diagnostics.CodeAnalysis;

    [assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:PrefixLocalCallsWithThis")]
    [assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1126:PrefixCallsCorrectly")]
    [assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1200:UsingDirectivesMustBePlacedWithinNamespace")]
    [assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1305:FieldNamesMustNotUseHungarianNotation")]
    [assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1309:FieldNamesMustNotBeginWithUnderscore")]
    [assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:FieldsMustBePrivate")]
    [assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1404:CodeAnalysisSuppressionMustHaveJustification")]
    [assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:ElementsMustBeDocumented")]
    [assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:EnumerationItemsMustBeDocumented")]
    [assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:PropertySummaryDocumentationMustMatchAccessors")]
    [assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:FileMustHaveHeader")]
    [assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1634:FileHeaderMustShowCopyright")]
    [assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:FileHeaderFileNameDocumentationMustMatchTypeName")]

**Comment by RobSiklos** [comment]
Why not just disable those rules via a `Settings.StyleCop` file?

**Comment by agray** [comment]
Thanks @RobSiklos,  I'll give it a go.  Is the Settings.Stylecop file supported functionality through the [StyleCop.MSBuild](https://www.nuget.org/packages/StyleCop.MSBuild/) nuget package?

This is how we are consuming this functionality.

**Comment by agray** [comment]
Found my answer [here](http://stackoverflow.com/questions/29190456/where-is-the-stylecop-configuration-file).

Thanks

**Comment by SanjayGuntur** [comment]
@agray , if your issue is resolved, can you help close this ticket?

**Comment by SanjayGuntur** [comment]
Closing as there is no response, feel free to re-open if required.
