### ISSUE TITLE
SA0102 syntax error using C# 7.0 ValueTuple

### ISSUE THREAD

**Issue by matman13** [StyleCop/StyleCop#104]
The following property getter is causing SA0102 syntax errors:

`public List<(IPEndPoint Source, IPEndPoint Destination)> ConnectionEndpoints { get; }`

Note this is using the new C# 7.0 ValueTuple syntax.

**Comment by Dutchdre** [comment]
Same here for ValueTuples in method return statements.

**Comment by carl-berg** [comment]
There still seems to be a problem with nullable tuples like this function for example: 
`public (SomeType a, string b)? DoSomething(...)`.

**Comment by apryshchepa** [comment]
I also receive SA0102 for method signatures like following:

private (Mynamespace.Myclass model, bool isReceived) ValidateModel(MyClass parameter)

**Comment by rovinbhandari** [comment]
This is 100% reproducible and should be opened again. Here's a simple example which results in SA102:

    (string, string)[] arr = {("foo", "bar"), ("baz", "qat")};
