### ISSUE TITLE
Line offset after multline strings with verbatim string literal

### ISSUE THREAD

**Issue by MSPChristian** [StyleCop/StyleCop#105]
StyleCop has an line offest if you use multline strings with verbatim string literal.

**Comment by RobSiklos** [comment]
@MSPChristian Can you provide more detail about the problem? Like the associated rule ID, the expected result, and the actual result?

**Comment by MSPChristian** [comment]
@RobSiklos Thanks for your fast response.

Sometimes I use multiline strings with prefix $@. In this case is a line offset.

One line, all is correct:
![markcorrect](https://cloud.githubusercontent.com/assets/26733972/25235318/15272ef6-25e5-11e7-87de-0343a06aa07f.PNG)

Multi line, offset for every line:
![markincorrect1](https://cloud.githubusercontent.com/assets/26733972/25235317/15217d80-25e5-11e7-9a68-914ec1e3d301.PNG)
![markincorrect2](https://cloud.githubusercontent.com/assets/26733972/25235319/1528dc4c-25e5-11e7-89cd-e0a64a662543.PNG)
![markincorrect3](https://cloud.githubusercontent.com/assets/26733972/25235316/152095a0-25e5-11e7-9bff-c7da707f21b3.PNG)

This occure wiht various rule id. In my exmaple it is SA1600.

**Comment by RobSiklos** [comment]
@MSPChristian It's unlikely that the SA1600 (Elements Must Be Documented) rule is being violated in this case. Can you check again for the ID of the rule that's being triggered here?

If you can't find it, perhaps the best thing would be for you to attach a minimal sample project which we can use to reproduce the behaviour.

**Comment by MSPChristian** [comment]
@RobSiklos Please find attached a small solution.

[DummyStyleCop.zip](https://github.com/StyleCop/StyleCop/files/1007498/DummyStyleCop.zip)

The different is in Line 22 of classes Example1 and Example2. 

Without $ in Example1 is everything okay. 

![example1](https://cloud.githubusercontent.com/assets/26733972/26151564/b1242056-3b03-11e7-9a2a-f260ac83823b.PNG)

With $ in Example2 you have an Offset and the wrong line is marked.

![example2](https://cloud.githubusercontent.com/assets/26733972/26151573/b7ac48c2-3b03-11e7-8910-4a96fa0c0049.PNG)

**Comment by MSPChristian** [comment]
@RobSiklos Any news?

**Comment by SanjayGuntur** [comment]
Thanks for the sample file, I was able to use that and your screenshots to repro the issue. Looking into it.
