### ISSUE TITLE
SA0102 syntax error when using C#7 local functions

### ISSUE THREAD

**Issue by cmeeren** [StyleCop/StyleCop#109]
Title says it all, I guess.

**Comment by Tonyangl** [comment]
How to disable this rule?

**Comment by cmeeren** [comment]
Currently there is no way, see #108.

**Comment by cmeeren** [comment]
Note that using ReSharper's own Errors window ("Solution Errors"?) you can ignore them so that they don't show up in ReSharper's analysis. They will however still be highlighted in the editor.

**Comment by citizenmatt** [comment]
Unfortunately, this is outside of ReSharper's control. StyleCop has its own C# parser, which doesn't understand C#7 - it is the StyleCop parser that is giving these syntax errors. And if StyleCop encounters a syntax error, it stops processing the whole file.
