### ISSUE TITLE
Unable to use Code Cleanup when StyleCop is installed

### ISSUE THREAD

**Issue by cmeeren** [StyleCop/StyleCop#110]
I am unable to use Code Cleanup when StyleCop 2017.1 is installed.

**To reproduce:**

Install StyleCop and do any of the following:
* Press the keyboard shortcut for Code Cleanup (for me, <kbd>Ctrl</kbd>+<kbd>E</kbd>, <kbd>C</kbd>)
* Right-click in the editor and select Code Cleanup
* Right-click a file in the Solution Explorer and select Code Cleanup
* Use the menu: ReSharper | Edit | Cleanup Code

**Expected behavior:**

The Code Cleanup window is displayed.

**Actual behavior:**

Nothing happens. It is utterly impossible to get the Code Cleanup window to display when StyleCop is installed.

**Version info:**

* VS2015 15.1.26403.0
   * Note: The R# "About" Window says it's running in 15.**0**.26403.0
* R# Ultimate 2017.1 built April 02
* StyleCop 2017.1.0

**Other info:**

Note that Silent Cleanup works. It's just the Code Cleanup window that's never shown.

If I uninstall StyleCop, everything works as normal.

Could this be a compatibility problem with the new Code Cleanup window in R# 2017.1?

**Comment by cmeeren** [comment]
Furthermore, the "Code Cleanup" settings page is not shown. See the image. Note that the header says "Context Actions", which was the previously selected settings screen.

![image](https://cloud.githubusercontent.com/assets/7766733/24771385/c056bda6-1b0d-11e7-9f2c-bb3cd2280d06.png)

**Comment by DevHim** [comment]
+1

**Comment by MatzeG** [comment]
+1

**Comment by matkoch** [comment]
Hi @cmeeren,

that is something that unfortunately slipped through in my PR for porting to 2017.1. I'm at it already, and will try to unlist the plugin as soon as possible during that.

Sorry for the inconvience.

**Comment by citizenmatt** [comment]
New version is now available in the Extension Manager. Apologies for the inconvenience!
