### ISSUE TITLE
Stylecop 5 has no implicit exceptions for Hungarian notation

### ISSUE THREAD

**Issue by berndrausch** [StyleCop/StyleCop#115]
There seems to be a change between Stylecop 4.7 and Stylecop 5. Stylecop 5 only shows the explicit excpetions for Hungarian notation. Stylecop 4.7 also had implicit excpetions like "as", "is" and "on". If you run Stylecop 5, it will complain about variables starting with "is", Stylecop 4.7 won't do that.

Was that done on purpose or is it a bug?

![stylecop](https://cloud.githubusercontent.com/assets/27762466/25217212/510aa9f0-25a6-11e7-9250-8b8ff63cc36b.PNG)

**Comment by SanjayGuntur** [comment]
This is indeed a bug in deployment. It does not deploy the default settings file at the right location.
Should be fixed in next release.
