### ISSUE TITLE
Code cleanup removes header in 2017.1.1

### ISSUE THREAD

**Issue by msmolka** [StyleCop/StyleCop#118]
I think the issue #49 is occurring again in version 2017.1.1, in version 2017.1.0 all was correct.

**Comment by matkoch** [comment]
@msmolka this is likely to be a change in ReSharper itself. There will follow a 2017.1.2 bug fix release soon. You might want to hold on to that. A repro would be appreciated in any way.

**Comment by msmolka** [comment]
@matkoch I meant version of extension. Today I've update extension only  from 2017.1.0 to 2017.1.1 and it started removing headers.

**Comment by matkoch** [comment]
@msmolka okay sorry, that was not obvious :) Could you still try to setup a repro?

**Comment by msmolka** [comment]
@matkoch Definatlely some 2017 version, because all worked with Resharper 2017.1.1 and Visual Studio 2017

**Comment by msmolka** [comment]
Hmm, It looks the problem was with changes in default Code Cleanup settings. Are change the way which settings are responsible ? Previously it was only one StyleCop violations, now insert header and doc comments as well.

Any way. Looks working so you can close this one.

**Comment by matkoch** [comment]
@msmolka I cannot close the issue, since it's not directly in the StyleCop/StyleCop.ReSharper repository. But I guess you should be able doing that :)
