### ISSUE TITLE
StyleCop + StyleCop.ReSharper extensions @ Visual Studio 2017 + R# 2017

### ISSUE THREAD

**Issue by Mephystus** [StyleCop/StyleCop#123]
Hi,
I'm trying to setup Visual Studio 2017 and R# 2017 with **StyleCop** and **StyleCop.ReSharper** extensions, but it does not work.

I've installed **StyleCop** from Visual Studio extensions (it was the only option available):
![image](https://cloud.githubusercontent.com/assets/28352792/25665584/f9672b22-3015-11e7-94a8-4e112a625079.png)

I've installed **ReSharper.StyleCop** from R# Extension Manager:
![image](https://cloud.githubusercontent.com/assets/28352792/25665916/f03983d2-3016-11e7-8aa5-3d2363979299.png)

**ReSharper.StyleCop** is associated to StyleCop 4.7.54.0, but this version is not supported by VS 2017.
![image](https://cloud.githubusercontent.com/assets/28352792/25666101/6c8406ce-3017-11e7-89cb-c26326d383e5.png)

Because of this, the clean up (with R#) and merging the StyleCop settings doesn't work properly.

Will **StyleCop 4.7.54** be supported in Visual Studio 2017 or will **ReSharper.StyleCop** with **StyleCop 5.0** be available in R#2017?

**Comment by SanjayGuntur** [comment]
The current stylecop VS extension (5.0.6329.1) is still in beta. It was released early this week, and we will need to wait a bit before promoting it to a stable release.

The R# plugin is built against a stable version of stylecop binaries (note that 4.7.55 is the latest stable version). Again, we will need to wait a bit before R# plugin is rebuilt with new version of stylecop.


That said, both the VS extension and the R# plugin are supposed to work independent of each other. If you are not using c# 7 syntax, you shouldn't see any problems. If you can describe the problem(s) you see with your current setup, with more detail, maybe someone can help.

**Comment by Mephystus** [comment]
Hi,
From the website: https://github.com/StyleCop/StyleCop.ReSharper, it seems that R# plugin is built against **4.7.54** and not **4.7.55**.
I have **4.7.54** installed, but I had to include the StyleCop Extension (v5.0), otherwise the **StyleCop** menu would not be available in VS 2017.
![image](https://cloud.githubusercontent.com/assets/28352792/25701577/ebf32dba-30c4-11e7-9257-d22cfc2d2f77.png)

I have the projects merged with an existing StyleCop settings file, which has **en-GB** for culture analysis.
In the following example, R# shows a StyleCop violation but StyleCop has 0 violations (which is correct):
![image](https://cloud.githubusercontent.com/assets/28352792/25701880/3acdce30-30c6-11e7-99fd-ff260c3ab55b.png)

Changing the Initiali**s**es to Initiali**z**es will clear R# warning (incorrectly), but StyleCop highlights the violation:  
![image](https://cloud.githubusercontent.com/assets/28352792/25701911/63d69f8c-30c6-11e7-83a6-4a803cd0d1a2.png)
 
**Note**: I also have VS 2015 + StyleCop **4.7.54** + R# 2016 (with StyleCop extension) and everything is working.

**Comment by SanjayGuntur** [comment]
Hmm... Can't explain it. I just tested it on a sample project and both the vs extension and the r# plugin seems to honor the settings file at the project folder.

One possible explanation would be that the vs extension is hitting a settings file that sets the culture to en-GB, but the r# plugin is not. Can you confirm that the settings file that has en-GB as culture is in the path to your project folder?

**Comment by Mephystus** [comment]
I've tried with the settings file in the project path: 
![image](https://cloud.githubusercontent.com/assets/28352792/25706668/f69e1efa-30d8-11e7-924a-95c69dc1c66d.png)

And also specifying the exact file to merge:
![image](https://cloud.githubusercontent.com/assets/28352792/25706688/03d444fa-30d9-11e7-9288-4cda2786050f.png)

When I right click on the project and look at the StyleCop settings
![image](https://cloud.githubusercontent.com/assets/28352792/25706793/5b597880-30d9-11e7-98da-23eb6fbdc195.png)

It shows the correct culture, but R# still complains.
![image](https://cloud.githubusercontent.com/assets/28352792/25706816/7197b800-30d9-11e7-8624-ba7489047bdc.png)

I could uninstall all components (StyleCop + R#) and install it again.
Could you let me know what exact versions you (@SanjayGuntur) have installed?

**Comment by SanjayGuntur** [comment]
Apologies, I take back my statement, I misread SA1650 (spell check violation) for SA1642 and I had a another settings file that I created for another test that was misleading my test result.

I can reproduce the behavior now. I'll take a look, but it appears the culture specific resource files are not deployed by the r# plugin, and there might be a valid reason for that. Will check further and see what can be done.

**Comment by SanjayGuntur** [comment]
Same issue as #46

**Comment by matkoch** [comment]
After release of ReSharper 2017.2 I will publish a pre-release with StyleCop 5 referenced.

**Comment by csdahlberg** [comment]
5.0.0 (stable) was published yesterday.

**Comment by matkoch** [comment]
I've published a [pre-release version for ReSharper 2017.1](https://resharper-plugins.jetbrains.com/packages/StyleCop.StyleCop/2017.1.2-pre001).

**Comment by ivanrusso** [comment]
I have the same Issue with StyleCop 5
![image](https://user-images.githubusercontent.com/2790090/30971240-adc11554-a467-11e7-994f-377dfa896f66.png)

![image](https://user-images.githubusercontent.com/2790090/30971309-d11fd0da-a467-11e7-98b3-adc55ada0cba.png)

**Comment by lennartb-** [comment]
I have the same issue as @ivanrusso, I'm actually not sure what changed. Maybe the update to Resharper 2017.2?

**Comment by matkoch** [comment]
@ivanrusso can you confirm what @lennartb- described also works for you?

**Comment by StevenLiekens** [comment]
@matkoch I installed **only** the resharper extension (2017.2.1-pre001) and nothing else and I get the same results as @ivanrusso 

(VS2015)

![image](https://user-images.githubusercontent.com/1583241/32701705-949c94cc-c7da-11e7-94a5-d632cbb47b3c.png)

![image](https://user-images.githubusercontent.com/1583241/32701665-1a1433e0-c7da-11e7-90df-3d4f9a534d2f.png)

**Comment by StevenLiekens** [comment]
PS I'm not running **any** version of the VS plugin so I don't even understand where the StyleCop.dll information is coming from...

**Comment by mvonballmo** [comment]
I'm having the same issue as @StevenLiekens  and @ivanrusso (both with and without the VS StyleCop extension installed). I saw a reference to "Analyzers" above, but I haven't been using those. I'm getting this warning, but StyleCop seems to be working fine, except for a few syntax errors in the R# warnings panel that I have to ignore. I upgraded everything in the hopes that I would get the latest fixes for these syntax errors, but to no avail.

Maybe I have two new errors that haven't been fixed yet?

Here's the first one:

```
  return new DataConnectionSettings()
  {
    DefaultIsolationLevel = IsolationLevel.Snapshot,
    ["SpecialKeyOne"] = "ValueOne" // syntax error on this line
  };
```

And the second:

```
Assert.IsTrue(ValueTools.TryChangeType("true", out bool? nullableTest));
```

Are these new errors? If so, I'll just file issues. If not, then could they be due to the DLL conflict?

Let me know if you need more information. Thanks in advance.

**Comment by GuilhermeMorais** [comment]
Guys any workaround for the @StevenLiekens problem? This is also happening to me and a few friends I know.

**Comment by jplopes** [comment]
![image](https://user-images.githubusercontent.com/2210457/34259414-0bc73d3e-e65a-11e7-9c37-fba147810478.png)

Still happening with 2017.3.0. Can someone help?

**Comment by jplopes** [comment]
Is there any workaround to this issue?

**Comment by matkoch** [comment]
@jplopes, @GuilhermeMorais, @StevenLiekens are you having any other issues than the warning about version mismatch? The message itself is actually nothing to worry about. When StyleCop became stable, the assembly version changed, and we usually set the ReSharper extension to the same. This time I forgot to do this step, but I will adapt the build to check this in future versions. I will make a new release with the updated version number asap.

@mvonballmo so it's just about new C# syntax features? Have you checked the language level? Similar to this [SO question](https://stackoverflow.com/questions/31574543/resharper-setting-c-sharp-language-level-for-solution)?

**Comment by StevenLiekens** [comment]
It did work for me but can you explain what all do we need to install?

There's a bunch of StyleCop extensions at this point and it's not obvious what we're supposed to install or not.
- https://github.com/StyleCop/StyleCop/tags
- https://github.com/StyleCop/StyleCop.ReSharper/tags

Some of these look like they were just experiments but I can't tell them apart from the production versions.

**Comment by matkoch** [comment]
@StevenLiekens if you want live inspections shown in your editor, then you have to install the ReSharper extension. Installation is done via the extension manager (Alt+R,X). There is also a [change log](https://github.com/StyleCop/StyleCop.ReSharper/blob/master/CHANGELOG.md) located in the repository.

**Comment by StevenLiekens** [comment]
Okay and that's all I have to install? I don't have to run any MSI installers or anything?

**Comment by mvonballmo** [comment]
I have set the language level for my solution to 7 for both ReSharper and Visual Studio. ReSharper doesn't indicate a problem with the two lines I posted above, just StyleCop. The ReSharper error even says that "A syntax error has been discovered in file ...  on line ... [StyleCop rule SA102]".

I've got ReSharper 2017.3.1 with Visual Studio Enterprise 2017 15.5.3 and StyleCop for JetBrains 2017.3.0. I can file separate issues for the syntax errors outlined above, but it seems like you think that they shouldn't be happening. I'm also still seeing the "mismatched DLL" warning (StyleCop.dll: 5.0.6.6419.0 and StyleCop.ReSharper.dll: 5.0.6329.1) but you've indicated that is probably innocuous.

**Comment by jplopes** [comment]
@matkoch Well, when I try to use the menu options from the Style Cop extension, it gives an error:
![image](https://user-images.githubusercontent.com/2210457/34920606-2074616e-f96d-11e7-9859-a6d3632451e3.png)
But if I uninstall the Resharper extension, everything works.
Thanks.

**Comment by matkoch** [comment]
@mvonballmo that sounds rather like an issue in StyleCop itself.
@StevenLiekens depends on your needs, but the ReSharper extension doesn't require any other VS extensions.
@jplopes that sounds like https://github.com/StyleCop/StyleCop/issues/50

**Comment by ThielHater** [comment]
Like @Mephystus I would like to setup VS2017 with ReSharper, StyleCop and StyleCop.ReSharper but I get the same error as in #50. This problem is related to two issues on GitHub, therefore I'm not sure where to comment.
