### ISSUE TITLE
StyleCop doesn't understand inline variable declaration

### ISSUE THREAD

**Issue by HeikoAdams** [StyleCop/StyleCop#124]
When running StyleCop 5.0.6329.1 on a source file with inline variable declaration StyleCop raises the following error:

> SA0102 : CSharp.CsParser : A syntax error has been discovered in file _X_ on line _Y_.

BTW: I'm using Visual Studio 2017

**Comment by SanjayGuntur** [comment]
Can you provide some sample code that generates this error?

**Comment by HeikoAdams** [comment]
This is like the code that generates this error:

```csharp
myfunction(a, b, out int c, out int c)
```

**Comment by SanjayGuntur** [comment]
Just tested it and I don't see the error. 

Do you have resharper plugin installed? If so, can you provide the resharper version and the stylecop plugin version?

**Comment by HeikoAdams** [comment]
No, I've installed StyleCop from VisualStudio 2017 Addons-Manager

**Comment by cosmin-ciuc** [comment]
I too have noticed this problem related to inline variable declaration. On my computer if a split the method call on several lines, and place each input parameter on its own line, if I have an out var x I'll get an error saying that a comma does not follow the previous parameter.
I'm using Visual Studio 2017 and I have installed StyleCop.MSBuild 5.0.0-beta02 and StyleCop.Resharper 4.7.1000 (4.7.54).

**Comment by SanjayGuntur** [comment]
@cosmin-ciuc ,the R# plugin is still using the old parser which does not understand the new syntax. You will need to wait until it's updated to the latest stylcop core binaries.

The issue reported by @HeikoAdams is different, he does not have r# installed. I still can't reproduce his issue. There are a few unit tests for the case he reported, so i'm not sure why he is seeing this issue. Maybe if he can share the exact line that compiles, but stylecop can't understand, we can check further.

**Comment by HeikoAdams** [comment]
Strange thing. ATM I also can't reproduce this anymore. So closing it for now

**Comment by jnyrup** [comment]
I get the error when the out parameter is of type nullable.
```csharp
Dictionary<int, DateTime?> a = null;
a.TryGetValue(0, out DateTime? b);
```

These two snippets work
```csharp
Dictionary<int, DateTime> a = null;
a.TryGetValue(0, out DateTime b);
```

```csharp
Dictionary<int, DateTime?> a = null;
a.TryGetValue(0, out var b);
```

R# is not installed.
Using VS 15.3.3 and StyleCop 5.0.6419.0.

**Comment by SanjayGuntur** [comment]
I can repro the issue. Thanks for reporting it.
