### ISSUE TITLE
Can we use specified StyleCop setting file for MSBuild?

### ISSUE THREAD

**Issue by Blueve** [StyleCop/StyleCop#125]
I want to use StyleCop to check our team's code independent.

For now, I use the command below to run StyleCop check in console and collect the violation log.
```bash
msbuild /p:CustomAfterMicrosoftCSharpTargets="C:\Program Files (x86)\MSBuild\StyleCop\v4.7\StyleCop.Targets" SomeProject.csproj
```
My question is how to specify a custom StyleCop setting file rather than an existing StyleCop setting file in project folder? I want ignore all StyleCop setting in current project.

Thank you.

**Comment by SanjayGuntur** [comment]
Looking at Stylecop.Targets file, it does seem to allow specifying a override for settings file through StyleCopOverrideSettingsFile property

Try the following command and let us know how it goes
`
msbuild /p:CustomAfterMicrosoftCSharpTargets="C:\Program Files (x86)\MSBuild\StyleCop\v4.7\StyleCop.Targets" /p:StyleCopOverrideSettingsFile="OtherFolder\StyleCop.settings" SomeProject.csproj 
`

**Comment by Blueve** [comment]
Thanks SanjayGuntur!
Follow your hint, I notice that the code in `StyleCop.Target` is:
```xml
  <!-- Define StyleCopOverrideSettingsFile property. -->
  <PropertyGroup Condition="('$(SourceAnalysisOverrideSettingsFile)' != '') and ('$(StyleCopOverrideSettingsFile)' == '')">
    <StyleCopOverrideSettingsFile>$(SourceAnalysisOverrideSettingsFile)</StyleCopOverrideSettingsFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(StyleCopOverrideSettingsFile)' == ''">
    <StyleCopOverrideSettingsFile> </StyleCopOverrideSettingsFile>
  </PropertyGroup>
```
And we can add property `SourceAnalysisOverrideSettingsFile` to add override setting file config.
At last, the MSBuild command should be:
```shell
msbuild /p:CustomAfterMicrosoftCSharpTargets="C:\Program Files (x86)\MSBuild\StyleCop\v4.7\StyleCop.Targets";SourceAnalysisOverrideSettingsFile="<CustomeSettingFilePath>" SomeProject.csproj
```
Tested and it work!
Thank you : )

**Comment by anjdreas** [comment]
In case anyone from ReSharper StyleCop extension stumbles in here, I filed an issue to support `StyleCopOverrideSettingsFile` here: https://youtrack.jetbrains.com/issue/RSPL-6920
