### ISSUE TITLE
Line break "Before single-line comment" does not ignore commented-out code (////)

### ISSUE THREAD

**Issue by cmeeren** [StyleCop/StyleCop#127]
I experience the problem below using StyleCop 2017.1.1 for ReSharper 2017.1.2.

In Resharper Options > Code Editing > C# > Formatting style > Blank Lines, I have "Before single-line comment" set to 1. This gives the following preview in the Options dialog:

```c#
void Foo()
{
    var x = 5;

    // comment
    Call();
    ////CommentedCall();
}
```

However, when I make a file with this code and format it using Reformat Code, this is the output I get:

```c#
void Foo()
{
    var x = 5;

    // comment
    Call();

    ////CommentedCall();
}
```

Notice that a blank line was inserted above `////CommentedCall();`. This is contrary to the preview in the Options dialog. The commented call should be ignored and not get a blank line above.

I do not experience this problem after uninstalling the R# StyleCop plugin, even when using the exact same settings by adding the StyleCop settings file to the "My Computer" settings layer.

**Comment by matkoch** [comment]
@cmeeren I can't reproduce this. Is it still actual? Can you check your settings once again by going to `ReSharper | Options` (not via `Manage Options`), which is the accumulated view of effective settings.
