### ISSUE TITLE
Code analysis doesn't report rule SA1623.

### ISSUE THREAD

**Issue by SpindlerS** [StyleCop/StyleCop#128]
Hello,

I changed StyleCop in my project to use Analyzers. I made my ruleset and everything was fine
...until I noticed that VS **intellisense tells me a broken rule** (SA1623). But **code analysis does not**.
The rule is broken in my code so I expected a warning on code analysis as configured in the ruleset.

I checked:
* Changing other rules has an impact on code analysis
* Changing SA1623 to error has the expected effect on intellisense

Addition:
I also get no warning for SA1600. In stylecop.json I added:
`"documentPrivateElements": true,
"documentPrivateFields": true`
but it seems to have no effect. Company name and copyright text are known, there is no problem.
Intellisense continues to show everything correct.

Currently I use StyleCop.Analyzers 1.0.0.

I would appreciate any help.
best regards, Sören

**Comment by SanjayGuntur** [comment]
This repo is for the "classic" stylecop.
For analyzers, try posting at https://github.com/DotNetAnalyzers/StyleCopAnalyzers/

**Comment by SpindlerS** [comment]
Ooops, I'm sorry for that! But thanks for your answer.
