### ISSUE TITLE
R# 2017.2 Support

### ISSUE THREAD

**Issue by dmitriyse** [StyleCop/StyleCop#131]
Please add support for 2017.2 EAP
+ Upgrade StyleCop.CSharp.Dll to 5.0.0+ version.

**Comment by dmitriyse** [comment]
I created pull request with adoption to 2017.2, also I published unofficial build: https://github.com/dmitriyse/StyleCop.ReSharper/releases/tag/2017.2-eap8-01

**Comment by ramoneeza** [comment]
How install an unofficial build into Resharper???

**Comment by dmitriyse** [comment]
Please see this thread https://github.com/StyleCop/StyleCop/issues/93

**Comment by dmitriyse** [comment]
C# 7.0 partially supported. For example ValueTuples are supported, but Local functions are not.

**Comment by matkoch** [comment]
_Officially tracked here: https://github.com/matkoch/StyleCop.ReSharper/tree/2017.2. Extension will be updated with release of ReSharper 2017.2._

**Comment by matkoch** [comment]
I've published a [pre-release version for ReSharper 2017.1](https://resharper-plugins.jetbrains.com/packages/StyleCop.StyleCop/2017.1.2-pre001) with StyleCop 5.0.0 support.

**Comment by matkoch** [comment]
Just released.

For StyleCop 4.7.54
https://resharper-plugins.jetbrains.com/packages/StyleCop.StyleCop/2017.2.0

For StyleCop 5.0.0
https://resharper-plugins.jetbrains.com/packages/StyleCop.StyleCop/2017.2.1-pre0001
