### ISSUE TITLE
SA0001: System.ObjectDisposedException, Cannot access a closed registry key.

### ISSUE THREAD

**Issue by croesusmartin** [StyleCop/StyleCop#137]
Hi,

I would like to know if you have any updates on this issue that was posted on codeplex a while ago:
https://stylecop.codeplex.com/workitem/7460

When using StyleCop 4.7 in a multi-threaded build, we occasionally hit an "SA0001: An exception occurred while parsing the file: System.ObjectDisposedException, Cannot access a closed registry key. MSBUILD : error : Object name: 'HKEY_CURRENT_USER\Software\CodePlex\StyleCop'" error.

**Comment by croesusmartin** [comment]
We are still experiencing this issue from time to time... any update?

**Comment by valleyjo** [comment]
Our team has also hit this. Can we please get some updates here?

**Comment by PiDiBi** [comment]
same here

**Comment by luiz1919** [comment]
Any update, I am getting the same error while compiling in our build infrastructure:

SA0001 : CoreParser : An exception occurred while parsing the file: System.ObjectDisposedException, Cannot access a closed registry key.
Object name: 'HKEY_CURRENT_USER\Software\CodePlex\StyleCop'..

**Comment by SanjayGuntur** [comment]
Version 4.7 is not supported anymore.

I did go through the archived code over at codeplex and from what I can see, the registry is used only in the settings dialog.

Recommend you guys to look at [StylecopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers). There is a lot activity over there, and supported by a dedicated group of people. This is the future.

If for whatever reason you cannot switch to use StyleCopAnalyzers, consider upgrading to 6.0.6902.2.
Instructions are [here](https://github.com/StyleCop/StyleCop/blob/master/README.md).
