### ISSUE TITLE
Header Creation

### ISSUE THREAD

**Issue by mayermart** [StyleCop/StyleCop#14]
CodeCleanup creates empty copyright block while 
* "Update file header" disabled
* "File Header Text" empty 
* Rules SA16XX disabled via Settings.StyleCop at Solution-Level

**Comment by meh-uk** [comment]
I've seen that too actually. Very annoying.

**Comment by citizenmatt** [comment]
What are you expecting to see? Any chance you could attach (or gist) the settings?

**Comment by mayermart** [comment]
I expect to see nothing, but i see:
// --------------------------------------------------------------------------------------------------------------------
// \<copyright file="filename.cs" company="">
//
// \</copyright>
// --------------------------------------------------------------------------------------------------------------------

Settings: https://gist.github.com/mayermart/5d054d1d2fbd72ac2d5a

**Comment by DevHim** [comment]
I have the same problem, this is how the settings file look:

![image](https://cloud.githubusercontent.com/assets/13120730/10041903/4361fb9c-61e8-11e5-833a-e7a0530e8b28.png)

After running code-cleanup (where Stylecop rules are enabled) I get this, which I do not want:

![image](https://cloud.githubusercontent.com/assets/13120730/10041934/7a91ae46-61e8-11e5-9103-e0c253b4f6e1.png)

Are we missing some setting, or what?

**Comment by jplopes** [comment]
I also noticed that having this in the File Header Text configuration:
--------------------------------------------------------------------------------------------------------------------
<copyright file="$FILENAME$" company="CompanyName">
    Copyright (c) CompanyName. All rights reserved.
</copyright>
<summary>
</summary>
--------------------------------------------------------------------------------------------------------------------

when I run a cleanup i was expecting to see this:

// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ClassName.cs" company="CompanyName">
//   Copyright (c) CompanyName. All rights reserved.
// </copyright>
// <summary>
//   The ClassName.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

instead I got this:

// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ClassName.cs" company="">
// 
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

Thank you.

**Comment by citizenmatt** [comment]
@jplopes Do you have a config that can replicate this? I've found an issue where the plugin wasn't reading the settings files correctly, and I suspect it's fixed the issue, but it would be nice to test.

**Comment by jplopes** [comment]
Hope this helps:
[Settings.StyleCop.txt](https://github.com/StyleCop/StyleCop/files/35740/Settings.StyleCop.txt)
Thank you!

**Comment by citizenmatt** [comment]
Is that the right settings file? The `CompanyName` and `Copyright` `StringProperty` elements are in the wrong place - they should be in the `AnalyzerSettings` element of the `DocumentationRules` section. If I move them (and I'm working with my fixed-reading-settings version) they appear as expected.

However, the summary doesn't appear, because by default, the `FileHeaderMustHaveSummary` rule is disabled, and you're not overriding it in your settings file. Also, there isn't any file header text configuration template like you listed.

**Comment by jplopes** [comment]
Hi again,
Sorry, I did a really bad job at explaining myself.
The File Header Text configuration I was referring to is in Resharper->Options->Code Editing->File Header Text. I was hoping that having this filled in would override StyleCop Settings (if it makes any sense). Anyway, from what I now understand from your explanation, my settings where all wrong for what I was expecting to get. Sorry for wasting your time. Keep up the awesome work you've been doing with the "million" Resharper plugins you maintain. Thank you.

**Comment by citizenmatt** [comment]
Hmm. Yeah, I need to think about the overlap between ReSharper's file header and StyleCop. The current implementation kind of ignores this, but we'd get different results if the settings came from ReSharper rather than settings.stylecop. I'll open a new issue. Cheers! :+1:
