### ISSUE TITLE
SA1126 Occurs for Inline outs.

### ISSUE THREAD

**Issue by Alshain01** [StyleCop/StyleCop#146]
The new C# inline out declarations cause SA1126 to occur, which is invalid.  VS2017 complains if you don't inline the outs so VS and StyleCop are arguing against each other.

Example (this will throw SA1126):
```
this.MyMethod(out short size);
this.Size = size;
```

**Comment by berndrausch** [comment]
Same here. This is really annoying, because I love the new inline out parameters. Any chance that this will be fixed?

**Comment by Alshain01** [comment]
berndrausch, after posting this I realized the project has been replaced by StyleCop Analyzers.  Switch to that one, it's more up to date and integrates directly into Roslyn.
