### ISSUE TITLE
An exception occurred while loading one of the StyleCop add-ins

### ISSUE THREAD

**Issue by jozefizso** [StyleCop/StyleCop#150]
I cannot edit StyleCop settings in Visual Studio 2017 because of this error:

![image](https://user-images.githubusercontent.com/287778/30215512-7a2f0dc0-94b0-11e7-879d-23a410151edd.png)

```
---------------------------
StyleCop
---------------------------
An exception occurred while loading one of the StyleCop add-ins: System.TypeLoadException, Method 'get_Container' in type 'yWorks.yFiles.GraphML.Xaml.prjmakbchnsnsqdlssischginqsja' from assembly 'yWorks.yFilesWPF.Viewer, Version=2.4.0.3, Culture=neutral, PublicKeyToken=b863993f4744b742' does not have an implementation.
---------------------------
OK   
---------------------------
```

**Comment by SanjayGuntur** [comment]
This is sort of known issue, that occurs when you have both the visual studio extension and the R# stylecop plugin installed. See #50 for more information. You should see the same failure when you try to run stycop from the solution explorer or the editor.

As a workaround, you can type `>Resharper_Suspend` in the immediate window of visual studio. Then restart visual studio. Once you are done with editing your stylecop settings, you can type `>Resharper_Resume` to get your environment back to it's original state. Ugly workaround, but it's what I can suggest for now.

**Comment by jozefizso** [comment]
I see. I disable the StyleCop extensions for ReSharper and the error does not occur.
