### ISSUE TITLE
Extension installation fails when only Visual Studio 2013 is present on the machine

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [StyleCop/StyleCop#166]
**This happens when you have only Visual Studio 2013 installed on your machine.**

You cannot install StyleCop.vsix on Visual Studio 2013: this version range specification effectively restricts this extension to be installable only on 2012 versions of Visual Studio Professional/Premium/Ultimate:

https://github.com/StyleCop/StyleCop/blob/835e77396a9dfba5911eb4c75f3c979408d86d00/Project/Src/StyleCop.VisualStudio.VSIX/source.extension.vsixmanifest#L18

**Newer versions of VSIXInstaller.exe (VS2015 and onwards) perform relaxed validations on this version range — they ignore it and allow installation anyways.**

I'd suggest expanding this version range to `[11.0,16.0)` (or leave it open-ended: `[11.0,)`).

**P.S.:** VSIXInstaller log: "Found installed product" lists only 2013 versions:

```
1/12/2018 10:01:48 PM - Microsoft VSIX Installer
1/12/2018 10:01:48 PM - -------------------------------------------
1/12/2018 10:01:48 PM - Initializing Install...
1/12/2018 10:01:48 PM - Extension Details...
1/12/2018 10:01:48 PM - 	Identifier      : StyleCop.629EB7CC-69C2-43AC-9BC9-482B0F810C4E
1/12/2018 10:01:48 PM - 	Name            : StyleCop
1/12/2018 10:01:48 PM - 	Author          : Chris Dahlberg
1/12/2018 10:01:48 PM - 	Version         : 5.0.6419.0
1/12/2018 10:01:48 PM - 	Description     : Provides source code style and consistency tools.
1/12/2018 10:01:48 PM - 	Locale          : en-US
1/12/2018 10:01:48 PM - 	MoreInfoURL     : https://github.com/StyleCop/StyleCop
1/12/2018 10:01:48 PM - 	InstalledByMSI  : False
1/12/2018 10:01:48 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/12/2018 10:01:48 PM - 
1/12/2018 10:01:48 PM - 	Supported Products : 
1/12/2018 10:01:48 PM - 		Microsoft.VisualStudio.Community
1/12/2018 10:01:48 PM - 			Version : [12.0,16.0)
1/12/2018 10:01:48 PM - 		Microsoft.VisualStudio.Pro
1/12/2018 10:01:48 PM - 			Version : [11.0,12.0)
1/12/2018 10:01:48 PM - 
1/12/2018 10:01:48 PM - 	References      : 
1/12/2018 10:01:48 PM - 
1/12/2018 10:01:48 PM - Searching for applicable products...
1/12/2018 10:01:49 PM - Found installed product - Microsoft Visual Studio Ultimate 2013
1/12/2018 10:01:49 PM - Found installed product - Microsoft Visual Studio Premium 2013
1/12/2018 10:01:49 PM - Found installed product - Microsoft Visual Studio Professional 2013
1/12/2018 10:01:49 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
1/12/2018 10:01:49 PM - Found installed product - Global Location
1/12/2018 10:01:49 PM - Found installed product - ssms
1/12/2018 10:01:49 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by jberezanski** [comment]
> Newer versions of VSIXInstaller.exe (VS2015 and onwards) perform relaxed validations on this version range — they ignore it and allow installation anyways.

I believe it works that way because the Community SKU was introduced in VS 2015, so VSIXInstaller 2015+ will look at `<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[12.0,16.0)" />` and allow installation on Community and higher (because it knows that higher editions are a superset of Community), while earlier VSIXInstallers do not recognize this SKU, so they ignore this line.

The version range should definitely be fixed, but meanwhile one workaround is to install a free, lightweight product from the VS 2017 family, such as the Feedback Client - this will provide an updated VSIXInstaller.
