### ISSUE TITLE
Multiple separator lines in code cleanup

### ISSUE THREAD

**Issue by citizenmatt** [StyleCop/StyleCop#17]
From [this comment](https://github.com/StyleCop/StyleCop/issues/9#issuecomment-138862785) in #9

"I disabled the constructor/destructor documentation setting. We are using a "---------" separator line at the beginning and end of the documentation blocks which works fine for all other code elements, but on the constructors it wants the standard line:

Initializes a new instance of the <see cref="WhatEver"/> class.

But when using the separator line it doesn't seem happy and adds another one of those lines every time you clean up the code, I found files that had that line 5 times for each constructor :)"

**Comment by citizenmatt** [comment]
@markuskorbel - any chance you could share the settings file you're using?

**Comment by markuskorbel** [comment]
Sure, I will try to reproduce with the new plugin today (many thx by the way for porting it!!!) and upload settings file and full example here...

**Comment by markuskorbel** [comment]
Hi Matt,
Sorry took a day longer - get burried yesterday - I actually reviewed my stylecop settings today and these are the ones I'm using now - and also still cause the issue:

https://gist.github.com/markuskorbel/7b9b020982aaf0a02779

Example class that shows the behaviour when using stylecop enabled code cleanup on it:

https://gist.github.com/markuskorbel/563c235ad336534619d9

Disabling the StyleCop rules SA1642/SA1643 resolves the problem - but also the check...

Regards,
Markus
