### ISSUE TITLE
SA0102 : CSharp.CsParser Syntax Error: default keyword c#7.1?

### ISSUE THREAD

**Issue by ThomasGugler** [StyleCop/StyleCop#172]
`long? inputId = default;`
produces an error:
Warning		SA0102 : CSharp.CsParser : A syntax error has been discovered ..

**Comment by mvonballmo** [comment]
These other issue  are also parser-related: #171 , #170, #169, #168

**Comment by hemnstill** [comment]
> pull requests will continue to be accepted

Is this project still maintained?
