### ISSUE TITLE
StyleCop removes parentheses from interpolated string's ternary operator after cleanup (C# 6.0 feature).

### ISSUE THREAD

**Issue by mbrenk** [StyleCop/StyleCop#175]
Sample source:
bool success = true; string test = $"{(success ? "yes" : "no")}";

After cleanup:
bool success = true; string test = $"{success ? "yes" : "no"}";

Code after cleanup does not compile.
Affected by "Fix StyleCop violations". No reproduction when this step is disabled.

**Comment by matkoch** [comment]
Fixed in [2018.1.2](https://resharper-plugins.jetbrains.com/packages/StyleCop.StyleCop/).
