### ISSUE TITLE
Load custom StyleCop addins

### ISSUE THREAD

**Issue by citizenmatt** [StyleCop/StyleCop#18]
StyleCop can run custom addins, e.g. [StyleCop+](https://stylecopplus.codeplex.com), that provide custom rules. These are normally handled by automatically loading the addins from the install folder. The ReSharper extension doesn't have an install location, so there is no way of loading custom addins. Either load addins from known locations, or provide a setting in options to specify one or more addin locations.

(See [this comment](https://github.com/StyleCop/StyleCop/issues/9#issuecomment-141944923) - #9)

**Comment by zynthar** [comment]
I would love to see support for StyleCop+! :+1:
