### ISSUE TITLE
StyleCop Resharper vs Resharper 2018.1 StyleCop native rules support

### ISSUE THREAD

**Issue by msmolka** [StyleCop/StyleCop#181]
I've notice in latest resharper there is native support for StyleCop rules.
https://blog.jetbrains.com/dotnet/2018/04/09/stylecop-code-style-settings-inspections/

My question is, do we still need this extension? Or all is build in?

**Comment by matkoch** [comment]
The built-in support doesn't yet cover all the rules. For instance, ReSharper currently has no inspections similar to the documentation rules.
