### ISSUE TITLE
C# 7.1 nullable local functions - SA0102 : CSharp.CsParser : A syntax error

### ISSUE THREAD

**Issue by maxacoustic** [StyleCop/StyleCop#185]
Parsing nullable local functions causes "SA0102 : CSharp.CsParser : A syntax error".
For example:

```c#
public class Foo
{
    public bool Bar(object buz)
    {
        return Check(buz) ?? false;
        
        bool? Check(object target) // Syntax error
        {
            ...
        }
    }
}
```

This happens because "StyleCop.CSharp.CodeParser.IsLocalFunctionStatement(bool)" method declared in "Project\Src\StyleCop.CSharp\CodeParser.Statements.cs" contains error.

When parser finds "bool" symbol from example above, it's tries to get and analyze the next symbol. In line 585:

```c#
while (true)
{
    // Get the symbol next to the proposed type declaration symbol.
    Symbol symbol = this.PeekNextSymbolFrom(testPosition, SkipSymbols.WhiteSpace, false, out testPosition);
```

After execution "symbol" is set to "?". And there are several conditional blocks below, that tries to expect the type of the symbol next to the "symbol" value and set it into the "expectingNextSymbolType" variable. All of them does not fires at symbol "?". Finally, "IsLocalFunctionStatement" returns at the line 636:

```c#
// We are at the right place, evaluate our expectation that next symbol is open paranthesis, or <.
Symbol nextSymbol = this.PeekNextSymbolFrom(testPosition, SkipSymbols.WhiteSpace, false, out testPosition);
return symbol.SymbolType == SymbolType.Other 
    && (nextSymbol.SymbolType == SymbolType.OpenParenthesis || nextSymbol.SymbolType == SymbolType.LessThan);
```

"nextSymbol" variable takes the value "Check" with type "Other". So "IsLocalFunctionStatement" return false, which is wrong.

To solve this issue, we need to add another one conditional block into the loop:

```c#
// Skip, if we are still reading nullable return type
if (symbol.SymbolType == SymbolType.QuestionMark)
{
    continue;
}
```

In this case, at the next iteration "symbol" variable will take "Check" value with type "Other", "nextSymbol" variable will take "(" value with type "OpenParenthesis", and expression in return statement will be evaluated to "true".

Sorry for my English.

**Comment by SanjayGuntur** [comment]
Can you add a test for this case?

**Comment by SanjayGuntur** [comment]
I will add some test for this soon.
