### ISSUE TITLE
2018.1.1 Click doesn't work

### ISSUE THREAD

**Issue by rdethurens** [StyleCop/StyleCop#187]
Hi everyone,

Sine I update my StyleCop package with resharper extension manager from 2018.1 to 2018.1.1, I've got a painfull bug on VS2017.

For exemple, it propose  : moving using inside namespame. 
When I clicked in the contextual menu on move, nothing happens.

Do you experience this kind of trouble ? Is there any way to downgrade my version ?

Thanks for your reply

**Comment by matkoch** [comment]
Which ReSharper version do you have installed (i.e. not the StyleCop extension version)?

**Comment by rdethurens** [comment]
Hi thanks for your reply,
I m on Resharper Ultimate 2018.1.
I will check your link in a moment

**Comment by matkoch** [comment]
I think you need to install the bugfix release of ReSharper.

**Comment by rdethurens** [comment]
I check my setting like the documentation and restart Visual but doesn't work.

I will try and say you installing the new resharper version. Thanks i'll give you feedback

**Comment by rdethurens** [comment]
That's rock after updating resharper. Thank you matkoch you save my happyness
