### ISSUE TITLE
How to uninstall StyleCop?

### ISSUE THREAD

**Issue by aubergine10** [StyleCop/StyleCop#190]
I downloaded installer via download button [in VS marketplace](https://marketplace.visualstudio.com/items?itemName=ChrisDahlberg.StyleCop) and installed to try it out.

However, there doesn't seem to be any way of uninstalling it (it's not listed in Control Panel > ... > Uninstall Programs).

How to uninstall?

**Comment by matkoch** [comment]
Should be in VisualStudio menu Tools | Extensiond and Updates.

**Comment by aubergine10** [comment]
That worked, thanks!
