### ISSUE TITLE
SA0102 Issue in StyleCop 4.7.44 - Syntax error

### ISSUE THREAD

**Issue by anildhandargmail** [StyleCop/StyleCop#208]
The functions with Async override and virtual keywords are reporting **Syntax error - SA0102**

Example - 
 public override async Task CallApiAsync()
 {
....

public virtual async Task<string> CallRestApiAsync(
...

**Comment by SanjayGuntur** [comment]
4.7.44 is not supported anymore. 

Recommend you to look at [StylecopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers).

If for whatever reason you cannot switch to use StyleCopAnalyzers, consider upgrading to 6.0.6902.2.
Instructions are [here](https://github.com/StyleCop/StyleCop/blob/master/README.md).

**Comment by powerdude** [comment]
@SanjayGuntur does the resharper plugin work with StylecopAnalyzers?

**Comment by SanjayGuntur** [comment]
No. But you should find similar features are available with the analyzer. If there is a specific feature that you want to know more about, you can post a question in their repo.

**Comment by powerdude** [comment]
@SanjayGuntur I'm more interested in code cleanup, so, if you know, will Resharper, with or without the plugin, do cleanup with the analyzer?
