### ISSUE TITLE
SA1203 conflicts with SA1202 on private const with public static fields

### ISSUE THREAD

**Issue by Predictor** [StyleCop/StyleCop#209]
The following code breaks **SA1202**:
`namespace Class1
{
    public class Class1
    {
        private const string Foo = "foo";
        public static readonly string[] Bar = { Foo };
    }
}`

If you swap the lines, it breaks **SA1203**:
`namespace Class1
{
    public class Class1
    {
        public static readonly string[] Bar = { Foo };
        private const string Foo = "foo";
    }
}`

"StyleCop.Analyzers" Version="1.1.1-rc.94"

**Comment by SanjayGuntur** [comment]
Please post this issue at [StyleCopAnalyzers ](https://github.com/DotNetAnalyzers/StyleCopAnalyzers)repo.
