### ISSUE TITLE
SA1100: DoNotPrefixCallsWithBaseUnlessLocalImplementationExists doesn't handle generic methods

### ISSUE THREAD

**Issue by davkean** [StyleCop/StyleCop#210]
Base:
``` C#
        protected T GetActiveConfiguredProjectExports<T>(ConfiguredProject newActiveConfiguredProject)
            where T : ConfiguredProjectExports
        {
            Requires.NotNull(newActiveConfiguredProject, nameof(newActiveConfiguredProject));

            return newActiveConfiguredProject.Services.ExportProvider.GetExportedValue<T>();
        }
```

Derived:

``` C# 
        protected override ConfiguredProjectExports GetActiveConfiguredProjectExports(ConfiguredProject newActiveConfiguredProject)
        {
            Requires.NotNull(newActiveConfiguredProject, nameof(newActiveConfiguredProject));

            return base.GetActiveConfiguredProjectExports<MyConfiguredProjectExports>(newActiveConfiguredProject); // <!--- Fires on this call
        }
```

**Comment by davkean** [comment]
This issue was moved to DotNetAnalyzers/StyleCopAnalyzers#2880

**Comment by allves90-star** [comment]
> Base:
> 
> ```cs
>         protected T GetActiveConfiguredProjectExports<T>(ConfiguredProject newActiveConfiguredProject)
>             where T : ConfiguredProjectExports
>         {
>             Requires.NotNull(newActiveConfiguredProject, nameof(newActiveConfiguredProject));
> 
>             return newActiveConfiguredProject.Services.ExportProvider.GetExportedValue<T>();
>         }
> ```
> 
> Derived:
> 
> ```cs
>         protected override ConfiguredProjectExports GetActiveConfiguredProjectExports(ConfiguredProject newActiveConfiguredProject)
>         {
>             Requires.NotNull(newActiveConfiguredProject, nameof(newActiveConfiguredProject));
> 
>             return base.GetActiveConfiguredProjectExports<MyConfiguredProjectExports>(newActiveConfiguredProject); // <!--- Fires on this call
>         }
> ```

``
