### ISSUE TITLE
Support for R# 10

### ISSUE THREAD

**Issue by DevHim** [StyleCop/StyleCop#22]
Believe support for R# 10 would be added soon? Would love to have that asap.

**Comment by meh-uk** [comment]
Agreed

**Comment by citizenmatt** [comment]
Yep, planning on having it out tomorrow.

**Comment by denisivan0v** [comment]
Any news here?

**Comment by wilhen01** [comment]
+1 :)

**Comment by citizenmatt** [comment]
Yes, didn't manage to get it done last week :(

On the plus side, I'm working on it right now, just trying to get StyleCopPlus working. About to implement a hack that is slightly less dirty than the hack that is already there :)

**Comment by denisivan0v** [comment]
Thanks for your efforts!
Maybe you can separate this two features - R# 10 and StyleCopPlus support - and release them independently?

**Comment by DevHim** [comment]
Hi Matt, Any ETA on this?

**Comment by citizenmatt** [comment]
Hi all. This is available on the Extension Manager - search for "StyleCop by JetBrains". (Long story short, there are two versions of StyleCop on the extension gallery. I'd love to merge them, but the other project's owner isn't responding)

**Comment by wilhen01** [comment]
Thanks for this @citizenmatt, installed and working perfectly :+1:

**Comment by denisivan0v** [comment]
Thanks @citizenmatt! I've already installed it
