### ISSUE TITLE
VS2017 SA0102 error with "default(string[])" 

### ISSUE THREAD

**Issue by wenqingzhang** [StyleCop/StyleCop#223]
**Given** C# code
```cs
return default(string[]);
```
**Run**  StyleCop in Visual Studio 2017
**Result** Got error below

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | SA0102 : CSharp.CsParser : A syntax error has been discovered in file D:\Work\Test.cs on line 4. | Test | D:\Work\Test.cs | 4 |  

But everything goes well in VS2019

**Comment by jakubbloksa** [comment]
I have the same problem with
`default(char[])`

- VS2017
- StyleCop.MSBuild (6.1.0)

**Comment by Fabi0San** [comment]
I noticed all default literals for array types where broken, here is a PR with the fix: #235

**Comment by csdahlberg** [comment]
This should be fixed by #235
