### ISSUE TITLE
SA0102 : CSharp.CsParser : A syntax error has been discovered in file containing interpolation string with escaped quotes

### ISSUE THREAD

**Issue by NikolayIT** [StyleCop/StyleCop#24]
Warning		SA0102 : CSharp.CsParser :
    A syntax error has been discovered in file [path]\ImageOptimizer.cs on line 22

Code to reproduce:

    namespace NotImportant
    {
        using System;
        using System.Diagnostics;
        using System.IO;

        public class ImageOptimizer : IImageOptimizer
        {
            public byte[] OptimizePng(string optimizerExecutable, byte[] fileContent)
            {
                var fileName = Path.GetTempPath() + Guid.NewGuid() + ".png";
                try
                {
                    // PNG file path.
                    File.WriteAllBytes(fileName, fileContent);

                    // Run OPTIPNG with level 7 compression.
                    var info = new ProcessStartInfo
                                   {
                                       FileName = optimizerExecutable,
                                       WindowStyle = ProcessWindowStyle.Hidden,
                                       Arguments = $"\"{fileName}\" -o7"
                                   };

                    // Use Process for the application.
                    using (var exe = Process.Start(info))
                    {
                        exe.WaitForExit();
                    }

                    return File.ReadAllBytes(fileName);
                }
                finally
                {
                    try
                    {
                        File.Delete(fileName);
                    }
                    catch
                    {
                    }
                }
            }

            public bool OptimizePng(string optimizerExecutable, string filePath)
            {
                try
                {
                    // Run OPTIPNG with level 7 compression.
                    var info = new ProcessStartInfo
                                   {
                                       FileName = optimizerExecutable,
                                       WindowStyle = ProcessWindowStyle.Hidden,
                                       Arguments = $"\"{filePath}\" -o7"
                                   };

                    // Use Process for the application.
                    using (var exe = Process.Start(info))
                    {
                        exe.WaitForExit();
                    }

                    return true;
                }
                catch
                {
                    return false;
                }
            }
        }
    }

Line 22 is:

    Arguments = $"\"{fileName}\" -o7"

**Comment by citizenmatt** [comment]
StyleCop doesn't support C# 6, because the custom parser it uses hasn't been updated. I suggest using the [DotNetAnalyzers/StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) instead. This has full support for C# 6, including a few new rules, as well as full support for the existing StyleCop rules (apart from spell check, I think).

**Comment by citizenmatt** [comment]
Closing in favour of #42

**Comment by TheSerVir** [comment]
I think, that issue wasn't fixed. I am using latest version of StyleCop at this moment (v4.7.55).
When i write something like this:
`string someString = $"somestring: \"{documentType}content\" somestring {itemNumber}]";`
and run stylecop, i will have a SA0102 error. That's appears, when we use interpolation with strings and ecaped quotes. Please, check this issue again.

**Comment by SanjayGuntur** [comment]
I did a quick test and cannot repro this the latest version (5.0.6329.1) which is output from the repo.

**Comment by TheSerVir** [comment]
@SanjayGuntur sorry, but I don't know nothing about this version. We are using the latest version that Nuget can provide. When we can find 5.0.6329.1 in Nuget?

**Comment by SanjayGuntur** [comment]
https://www.nuget.org/packages/StyleCop.MSBuild/5.0.0-beta02
It's a prerelease version.
