### ISSUE TITLE
Support for configuration using EditorConfig

### ISSUE THREAD

**Issue by JadaVonRuth** [StyleCop/StyleCop#240]
Is there already a support for not having to use rulesets xml or json configuration files and use modern editorconfig where all rules from multiple analyzers including vs ide settings can be stored? If not is it in the plan?

**Comment by mikernet** [comment]
I am also very interested in having .editorconfig support for the settings. Would you guys take a PR for this feature if I worked on it?

**Comment by csdahlberg** [comment]
I would certainly consider it, but wouldn't that effort be better spent on adding support for that to [StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) instead of this no-longer-well-maintained StyleCop "Classic" project?

**Comment by mikernet** [comment]
My apologies, that's actually where I meant to post this, googling "stylecop .editorconfig" just brought e me here and I apparently wasn't paying enough attention to realize I was in the wrong repo 😅

**Comment by JadaVonRuth** [comment]
I also meant stylecop analyzer not classic one

**Comment by csdahlberg** [comment]
For anyone else finds this looking for StyleCopAnalyzers, here's an issue about it over in that project: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3045
