### ISSUE TITLE
StyleCop as a dotnet tool utility?

### ISSUE THREAD

**Issue by FilBot3** [StyleCop/StyleCop#248]
Is it possible to make StyleCop work as a `dotnet tool` to be ran in a CI/CD environment or a scripted deployment?

**Comment by michaelvolz** [comment]
I use it in my CI/CD process during build. Just add this to your project or Build.props
```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
``` 
It will report any violation as an error. No need for a specialized tool IMHO.

**Comment by FilBot3** [comment]
Awesome, this did the trick. I had to fix another issue that popped up first after upgrades. Thank you!

**Comment by FilBot3** [comment]
To help clarify for the future, this works on `--configuration Release` builds.

```bash
dotnet publish --runtime linux-x64 --configuration Release
```
Then the SyleCop runs and causes failures for Warnings in your configs. By default it seems to include the `.csproj` XML. So fix that first.
