### ISSUE TITLE
SA 1512 - Clears blank line after file header.

### ISSUE THREAD

**Issue by dmitriyse** [StyleCop/StyleCop#26]
// <copyright file="abc.cs" company="comp">
// Copyright (c) comp project. All rights reserved.
// Licensed under the Apache 2.0 license. See LICENSE file in the project root for full license information.
// </copyright>
!!!!!! this blank line is deleted !!!!
namespace Comp.Code
{

But in this case is not cleared.

// <copyright file="abc.cs" company="comp">
// Copyright (c) comp project. All rights reserved.
// Licensed under the Apache 2.0 license. See LICENSE file in the project root for full license information.
// </copyright>
!!!!! this blank line is preserved !!!!
using System.Reflection;
using System.Resources;

![image](https://cloud.githubusercontent.com/assets/10322215/11324825/cae84614-9156-11e5-8eb1-3cbc5db713f1.png)

**Comment by citizenmatt** [comment]
Can you provide some more context, please? Code cleanup moves the using statements inside the namespace, so I don't know what steps you've used to get to the second example.

**Comment by dmitriyse** [comment]
![image](https://cloud.githubusercontent.com/assets/10322215/11447244/90804a12-955c-11e5-806b-f553a0499aa5.png)
Problem is that in some files header is delimited by line but in other not delimited.
Files reformated with the same settings.

Steps to reproduce.
1) Download and open solution from the link (https://www.dropbox.com/s/lvsrhprp96jgkm9/SA1512HeadersAndBlankLines.zip?dl=0)
2) Perform cleanup on all files with "MyCleanup" settings
You should get the same state as in provided screenshot.

I can increase resharper settings (blank lines after file headers) but in this case AssemblyInfo.cs files will be delimited by two lines and StyleCopAnalyzers will produce warning (two blank lines).

**Comment by citizenmatt** [comment]
Tested with the current version, and can't reproduce. There is no blank line after the header in either file. Please reopen if it's still an issue.
