### ISSUE TITLE
SA1000 conflicts with IDE0055 for simplified constructor calls

### ISSUE THREAD

**Issue by KieranDevvs** [StyleCop/StyleCop#261]
VS2019 suggests that 
`private readonly Type _typeInstance = new ();`
 is incorrect and should be 
 `private readonly Type _typeInstance = new();`

StyleCop suggests that 
`private readonly Type _typeInstance = new();`
 is incorrect and should be 
`private readonly Type _typeInstance = new ();`

When it comes to simplified constructors, I think VS is correct. 
Is there a way to configure StyleCop Analysers to unify the suggested outcome?

**Comment by ZakChar** [comment]
IMHO, the new keyword should have a rule that says that it needs to be followed by a space (classic new syntax), unless what is following is an open parenthesis (method call syntax).

**Comment by j2jensen** [comment]
FWIW the StyleCopAnalyzers people opted to fix this on their end (but the fix is still only available in a beta version of their nuget package).

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/3187
