### ISSUE TITLE
Extracting a method adds this. qualifier even if disabled in R#

### ISSUE THREAD

**Issue by HexWrench** [StyleCop/StyleCop#28]
I extracted a simple method using R#, and StyleCop added the "this." qualifier to all properties in the new method (e.g. this.Connection instead of just Connection). The "old" StyleCop doesn't do that (just tried it).

In R#, the setting "Use this. qualifier for" is set to "Preference: none" and "Do not show".

**Comment by citizenmatt** [comment]
What version of ReSharper are you using? I'm looking at 2016.1, and the "Use this. qualifier for" setting in C# Code Style has a drop down of Field, Property, Event and Method, and they're all selected. StyleCop isn't doing anything to set this, from what I can see.

**Comment by citizenmatt** [comment]
Ah, I think I misunderstood. If you override the default settings (which adds `this.`), then it's still getting added, right? I think this was a bug in ReSharper (10.0 IIRC). StyleCop itself doesn't add the `this`, just sets the default settings. Please can you try a newer version of ReSharper (10.0.2 or 2016.1) and see if things work the way they should?
