### ISSUE TITLE
R# StyleCop Inspections runs even if StyleCopAnalyzers plugged to project

### ISSUE THREAD

**Issue by dmitriyse** [StyleCop/StyleCop#30]
This problem is not on the top.
It appers only on scenario when single *.ruleset file attached to multiple projects "as link".
I prepared simple solution that can be used to reproduce problem.
Steps to reproduce:
1) Download and Open solution from this link (https://www.dropbox.com/s/yg3j2ifa3ns6qgk/StyleCopAnalyzersProblem.zip?dl=0)
2) Wait until solution is fully loaded
3) Load Missed nuget packages
5) Open Resharper->Inspect->Code issues in solution (this step is optional but it shows problem clearly)
6) Add to solution existing project DummyLib
7) Open Class1.cs in the DummyLib project
8) On Code issues window push refresh
StyleCopAnalyzers will not be detected for DummyLib project.
This is 100% workign way to reproduce the issue.

But when you load solution with multiple projects with ruleset attached as link, problem is appers with probability 1/3. So possibly if project loaded after R# stylecop do some action, StyleCopAnalysers can't be detected on that project.

Problem screenshot:
![image](https://cloud.githubusercontent.com/assets/10322215/11446591/99eef83c-9552-11e5-8440-7c876765e2be.png)

**Comment by Sharparam** [comment]
Having the same/similar issue with a single project using StyleCop.Analyzers with a custom ruleset file. If "Run StyleCop as you type" is enabled in the plugin it will run StyleCop on the code with all the default rules enabled, completely ignoring the ruleset file specified in the project settings.

[Link to directory in repo at relevant commit](https://github.com/CoraleStudios/Colore/tree/073273c99b78d3a18c0d2fdc3c3069ca4d11549c/Corale.Colore).
