### ISSUE TITLE
SA 0102

### ISSUE THREAD

**Issue by DMDTT** [StyleCop/StyleCop#31]
When using StyleCop as plugin in resharper 10 and using c#6 features like null conditionary expressions I get SA0102: CSharp.CsParser: A syntax error has been discovered in file...

example:

if (bla.Array?.Any() ?? false)

as this is a csparser rule, you can't supress it by settings file, is there a workaround?
I don't want to exclude the files from style cop parsing

**Comment by citizenmatt** [comment]
This version doesn't support C# 6. The plugin is using its own C# parser, not even using ReSharper's own syntax tree (another reason for performance issues), and hasn't been updated for C#6. If you're using Visual Studio 2015, I suggest you use the [DotNetAnalyzers/StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) project. This will give you StyleCop warnings and analysis, and the ReSharper StyleCop plugin will see that it's installed and disable its own analysis, but will leave other features, such as settings and code cleanup file layout still available.

**Comment by ohadschn** [comment]
Looks like null coalescing is still unsupported in the latest _StyleCop.MSBuild_ NuGet package (4.7.55 at the time of writing).
