### ISSUE TITLE
Duplicate StyleCop warnings in tooltips.

### ISSUE THREAD

**Issue by jonthegiant** [StyleCop/StyleCop#34]
This is just one example, but every StyleCop warning is displayed three times on tooltips.
Offending code:
```csharp
private void Main_FormClosing(object sender, FormClosingEventArgs e)
```
Mouse Over tooltip:
![2016-01-04_09-25-17](https://cloud.githubusercontent.com/assets/5591930/12092735/7aa24c1a-b2c4-11e5-8c99-09f0d187598e.png)

VS 2013, R# Ultimate 10.0.1
Only two extensions installed:
* Enhanced Tooltip 2.7.1.17,
* StyleCop by JetBrains 4.8.0

I've tested the issue with enhanced tooltip installed/uninstalled - same problem.

**Comment by pkunze** [comment]
Same for VS 2015 Community, only StyleCop by JetBrains 4.8.0 installed

**Comment by citizenmatt** [comment]
Is there anything special going on with the solution? Is it shared projects? Can you share the project?

**Comment by pkunze** [comment]
No. Maybe its helpful to point out thet this didn't happen when I was using VS 2013 and Resharper 8...

**Comment by msmolka** [comment]
I have only one extension StyleCop by JetBrains 4.8.0, and have the same issue. It is clean system. R# 10.0.0.2. And every stylecop issue is displayed 3 times.

**Comment by citizenmatt** [comment]
I can't reproduce this - I only get one tooltip. I'm about to push a new version for ReSharper 2016.1, which is only showing one tooltip. Could you check with the new version when it's available, please? (Hopefully in a couple of hours)

The errors shown by the installer are benign - it's trying to load the plugin to look for custom build steps (there aren't any) and the layout of the plugin on disk means it can't load the Rules assembly. It still installs correctly.

**Comment by citizenmatt** [comment]
Aha. Found a repro. It's due to a file that depends on another file, e.g. `.xaml` and `.xaml.cs`. Unfortunately, the ReSharper plugin is passing in the single file multiple times, rather than all of the dependent files.
