### ISSUE TITLE
Unable to install extension package within R# 10.0.0.2

### ISSUE THREAD

**Issue by CrispinParker** [StyleCop/StyleCop#35]
I'm having a tuff time getting the extension package to install under R# 10.0.0.2.

The installation process chugs away and then prompts a VS restart. After the restart the extension is still not installed. Worked fine under R# 10.0.0.1.

StyleCop is installed within VS2015 and can be run via the solution explorer context menu options. The warnings appear in the build error list as expected. 

Incidentally, what's dependencies for the SCbyJB extension? I've tried installing SC from the old CodePlex MSI and using the "Visual StyleCop" VS extension and both! Still no joy.

Any help greatly appreciated!

**Comment by citizenmatt** [comment]
Please can you post the latest installer log file from `%LOCALAPPDATA%\JetBrains\Shared\v04`?

There are no external dependencies for this extension, it's all self contained. But the extension ships as several assemblies that have references between them (and the [installer error mentioned here](https://youtrack.jetbrains.com/issue/RSRP-450976) is due to these references not being loaded)

**Comment by CrispinParker** [comment]
Attached is the installer logs from another attempt to add the extension.

Strangely, I can't see any mention of "StyleCop" in that log?! I'm defiantly selecting it within the extension manager.

[InstallerLog020.txt](https://github.com/StyleCop/StyleCop/files/79739/InstallerLog020.txt)

**Comment by citizenmatt** [comment]
Hmm. Odd that you can't see StyleCop in the log. Can you try and remove all folders that contain "StyleCop" in the `%LOCALAPPDATA%\JetBrains\plugins` and try to install "StyleCop by JetBrains" again, please? I presume you don't have any other plugins installed, right?

**Comment by CrispinParker** [comment]
Yay fixed it!!!

I checked the plugins folder you indicated, but it contained no sub folders. However, what it did contain was a NuGet "repositories.config" file. inside the config file was a pointer to a location under my profiles "Roaming" folder: 

<repository path="..\..\..\Roaming\JetBrains\ReSharperPlatformVs14\v04\packages.config" />

Investigation of the packages.config file showed that StyleCop.StyleCop package was already listed:

<package id="StyleCop.StyleCop" version="4.8.0" />

Removing that entry then allowed the R# extension manager to correctly install the package. So it appears that the issue was a combination of NuGet and R# Extension manager not playing nicely.

Anyway, you'll be glad to hear that your StyleCop plugin appears to work flawlessly in VS2015. Well done and thanks for all the pointers.


Many thanks,

Crispin.

**Comment by citizenmatt** [comment]
Glad you got it installed! I haven't seen that issue before, nice to know, and I'll file it away for future reference. Thanks!
