### ISSUE TITLE
Filtering Inspections Report by StyleCop categories is not working as expected

### ISSUE THREAD

**Issue by sam-piper** [StyleCop/StyleCop#37]
In R# 10.0.2 / StyleCop 4.8.0, I ran an inspection report for the solution, to pick up any existing StyleCop rule violations as well.

This returned several tens of thousands of items, also expected, including a number of StyleCop rules.

I then went to the Filter function, and included only StyleCop categories, and suddenly I had 0 results, even though in the previous view there were clearly StyleCop rule violations that were listed within the StyleCop categories I was trying to filter by.

**Comment by schlotter** [comment]
Is see this again with StyleCop by JetBrains 2017.1.1 in ReSharper 2017.1.3. Can you confirm?
