### ISSUE TITLE
Using statements are being relocated even with SA1200 turned off.

### ISSUE THREAD

**Issue by wiredwiz** [StyleCop/StyleCop#38]
I turned off SA1200 in a StyleCop settings file and put it in my solution folder.  I then ran code cleanup on a file and the add-in still relocated my using block.  I have attached my StyleCop settings file.

Before:
```C#
using System;
using System.Collections.Generic;
using Org.Edgerunner.Common.Buffers.Input;

namespace Org.Edgerunner.Common.Parsing.Tokens
{
   /// <summary>
   ///    Class that represents a single parsed language token.
   /// </summary>
```
After:
```C#
using System;

namespace Org.Edgerunner.Common.Parsing.Tokens
{
   using System.Collections.Generic;

   using Org.Edgerunner.Common.Buffers.Input;

   /// <summary>
   ///    Class that represents a single parsed language token.
   /// </summary>
```
[Settings.StyleCop.zip](https://github.com/StyleCop/StyleCop/files/105325/Settings.StyleCop.zip)

**Comment by citizenmatt** [comment]
Ah, this is the intersection between ReSharper features and StyleCop features. The inspection is SA1200, and a StyleCop feature, but moving the using statements is a ReSharper feature. The settings file that gets added (ReSharper &rarr; Manage Options &rarr; StyleCop) sets the C# Code Style "Add 'using' directive to deepest scope", which is the ReSharper cleanup for SA1200. If you uncheck this, it won't reorder your using statements any more.

**Comment by wiredwiz** [comment]
I don't quite understand.  If I go to ReSharper → Manage Options, there is no StyleCop option anywhere on this screen.  It just lists the different settings levels.  The only StyleCop sections I see are under Options and Tools, or the new Code Cleanup Profile, neither of which has the "Add 'using' directive to deepest scope" you are referring to.

**Comment by wiredwiz** [comment]
I found it under ReSharper → Options → Code Editing → C# → Code Style.

**Comment by citizenmatt** [comment]
Yep, sorry, that's where it is. You should have an "StyleCop.StyleCop » StyleCop" item (I could perhaps name that better :smile:) under Extensions in ReSharper → Manage Options. If you don't, can you check you've installed "StyleCop by JetBrains". If you've got "ReSharper.StyleCop", you should uninstall it - it's buggy.

**Comment by wiredwiz** [comment]
I do have that listed under manage options but I saw no way to get to the rule you were talking about from there.  I really wish there was a unified interface for editing and maintaining the rules, instead of some in resharper settings and some in the stylecop settings file.  That is one thing I very much preferred in ReSharper.StyleCop.
