### ISSUE TITLE
Using StyleCop for ReSharper to provide Company and Copyright Information

### ISSUE THREAD

**Issue by Abhith** [StyleCop/StyleCop#39]
How can we configure the company name and copyright text ?

`// ----------------------------------------------------
// <copyright file="HomeControllerRoute.cs" company="">
//   
// </copyright>
// <summary>
//   Defines the HomeControllerRoute type.
// </summary>
// ---------------------------------------------------------`

**Comment by Darxis69** [comment]
I don't think it is possible using just the StyleCop plugin for Resharper. It is possible using the standalone StyleCop (not the jetbrains plugin). It would be great though to have this feature :)

**Comment by citizenmatt** [comment]
Closing in favour of #44
