### ISSUE TITLE
c# parse error with property initializers

### ISSUE THREAD

**Issue by vitalych** [StyleCop/StyleCop#40]
class A {
public static int Prop { get; set; } = 1;
}

will give:
warning : SA0102 : CSharp.CsParser : A syntax error has been discovered in file...

**Comment by BrightLight** [comment]
That's C# 6 syntax. This StyleCop plugin does not support C# 6. For details see issue #12 ("The future of StyleCop?").
Basically, if you need support for C# 6 syntax you have to switch to [DotNetAnalyzers/StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers).

**Comment by citizenmatt** [comment]
Closing this in favour of #42. Working to merge with StyleCop on CodePlex to get their C#6 support.
