### ISSUE TITLE
This plugin is not showing in plugins list of ReSharper 10.1 EAP

### ISSUE THREAD

**Issue by NikolayIT** [StyleCop/StyleCop#41]
https://resharper-plugins.jetbrains.com/packages/StyleCop.StyleCop/ is only supported in R# 10 but not in 10.1 EAP (https://confluence.jetbrains.com/display/ReSharper/ReSharper+10.1+EAP)

**Comment by mvonballmo** [comment]
The plugin is still not showing up in 10.1 EAP4. Was there another significant plugin architecture change? There are very few extensions available right now, so it's not surprising that StyleCop is not showing up. Any idea when it will be supported?

**Comment by Lechus** [comment]
10.1 EAP5 still not showing.

**Comment by nunofilipecosta** [comment]
2016.1 Not showing ? Will there be a version for this ?

**Comment by citizenmatt** [comment]
Yep, a new version will be out this week. Closing this in favour of #47.
