### ISSUE TITLE
StyleCop does fail for files with C# 6 features 

### ISSUE THREAD

**Issue by ChrSteinert** [StyleCop/StyleCop#42]
I recently disvocered stylecop failing for certain files in VS15. But only some files seemed to be affected. I managed to break it down to files containing C# 6 features, like the conditional access operator (?.) or the new string interpolation ($"String with {variable}").

### Repo Steps 
Take a new C# class and use any C# 6 feature, like this close does:
```
using System;

namespace Repo
{
    class Program
    {
        public static void Main(string[] args)
        {
            string asd = $"{args[0]}";
        }
    }
}
```
StyleCop will not give any warnings about the using directive being out of the namespace or the class not having an access modifyer.
Now delete the '$' from the interpolated string - all warnings appear as expected.

**Comment by dfyx** [comment]
See #40 and #12

**Comment by ChrSteinert** [comment]
So this won't be fixed, although it would be realy nice to have it?

**Comment by dfyx** [comment]
Looks like it. For VS2015, StyleCopAnalyzers is recommended instead of this project.

**Comment by ChrSteinert** [comment]
True, but it offers way less, then the Resharper integration.
I understand that the problem of having multiple c# parsers around is not nice. But I'd really like to have this here. Would also try to contribute toward making it happen.
Let's see.

**Comment by DMDTT** [comment]
Dito!
https://stylecop.codeplex.com/

stylecop development restarted?! maybe there will be some future solution in some months for c#6
