### ISSUE TITLE
Please add support for Resharper 2016.1

### ISSUE THREAD

**Issue by msmolka** [StyleCop/StyleCop#47]
Please add support for latest resharper.

**Comment by wilhen01** [comment]
+1, just upgraded and was sad to discover I've lost Stylecop

**Comment by Jan-Olof** [comment]
+1

**Comment by Alano13** [comment]
+1

**Comment by BenKmann** [comment]
+1

**Comment by denisivan0v** [comment]
do you have any upgrade plans?

**Comment by citizenmatt** [comment]
Yes, it'll be out this week.

**Comment by wilhen01** [comment]
Thanks @citizenmatt!

**Comment by dawoe** [comment]
+1

**Comment by dawoe** [comment]
+1

**Comment by morinmartin** [comment]
+1

**Comment by hutton** [comment]
+1

**Comment by gf4t47** [comment]
+1

**Comment by UlrichFreiberg** [comment]
+1

**Comment by kaweera** [comment]
+1

**Comment by citizenmatt** [comment]
Sorry for the delay, everyone. I'm working on it, fixing a couple of bugs, it'll be out very soon.

**Comment by rkotulan** [comment]
Thanks, I am going to test it :)

**Comment by UlrichFreiberg** [comment]
Works like a charm - Super... Thx...

**Comment by wilhen01** [comment]
Yeah installed yesterday and working perfectly, thanks @citizenmatt!
