### ISSUE TITLE
Add 'Cleanup only source-control modified' files

### ISSUE THREAD

**Issue by Darxis69** [StyleCop/StyleCop#48]
Would be nice to add a checkbox 'Cleanup only source-control modified', so we don't have to manually select Cleanup every single files separately. 
The problem is that, when doing Cleanup Code on the whole Solution/Project, it cleanup files that are not source-control modified and thus sometimes, modifying them.

**Comment by citizenmatt** [comment]
This isn't really something that can be accomplished in the StyleCop plugin, but is a better fit for ReSharper itself. I've added an issue: [RSRP-458673](https://youtrack.jetbrains.com/issue/RSRP-458673)
