### ISSUE TITLE
StyleCop for Resharper 2016.1 code cleanup header/doc

### ISSUE THREAD

**Issue by msmolka** [StyleCop/StyleCop#49]
I have strange problem with insterting docs and header. 
I have StyleCopeAnlayzers added to project.

If there is no summary for constructor, code cleanup removes header and do not insert default summary. 
However if there is even empty summary for contructor, code cleanup insert file header. But still not insterts default default constructor documenation.

**Comment by caf-cyrusc** [comment]
I am seeing the exact same behaviour

R# 2016.1.2 / StyleCop by Jetbrains 2016.1.0

**Comment by citizenmatt** [comment]
Do you have a small project I can test this on, please?

**Comment by msmolka** [comment]
Hello
I'm trying to reproduce this issue with small app, and latest reshaper 2016.2 and stylecop 2016.2 and cannot. Looks like issue is solved. I will monitor and let you know, if it happen again

**Comment by citizenmatt** [comment]
Cool, thanks! I'll close for now, please reopen if you see it again.
