### ISSUE TITLE
TypeLoadException (method not implemented) when starting stylecop

### ISSUE THREAD

**Issue by GeneralSan** [StyleCop/StyleCop#50]
When I have the resharper extension "stylecop by jetbrains" not installed, everything seems to work fine.

When I installed the resharper extension I run the command ClassViewContextMenus ClassViewProject RunStyleCop, it shows me a message box titled StyleCop, with message "An exception occurred while loading one of the styleop addins: System.TypeLoadException, Method 'get_Container' in type 'somegarbledtype' from assembly 'yWorks.yFilesWPF.Viewer, Version=2.4.0.3, Culture=neutral,PublicKeyToke=sometoken'" does not have an implementation.

After uninstalling, the stylecop command runs fine again.

**Comment by citizenmatt** [comment]
Is this running the StyleCop command that's implemented by the Visual Studio plugin?

I wonder if this is an issue to do with the strong naming of the StyleCop.dll assemblies - it means both the ReSharper plugin and the VS plugin can ship different versions without problems, but if they ship the same version, either assembly can be used. But, if the VS code uses the ReSharper assembly, I bet it's trying to load the rules by looking at the folder containing the StyleCop.dll file, which is the ReSharper bin folder, and it's therefore having problems with the obfuscated yWorks assembly. Hmm.

Can you let me know the version numbers of ReSharper, the ReSharper StyleCop plugin and the VS StyleCop plugin, please?

**Comment by GeneralSan** [comment]
It is the Visual StyleCop extension command.

I use the official version of Resharper Ultimate. (no betas or anything)
Without looking up specific versions, I have installed the latest resharper
this morning (update from today/yesterday, so the absolutely latest
version).
There are no updates for the resharper stylecop extension, so this should
also be the latest version.
There are no updates for Visual StyleCop, so also the latest version.

To check the actual version numbers:
VS 2015 Update 2
Visual StyleCop 4.7.59.0
Resharper Utimate 2016.1.1
StyleCop by JetBrains 2016.1.0

---------------------------------------------------------
Met vriendelijke groeten,
Dirk Maegh

**Comment by citizenmatt** [comment]
Thanks. I do think it's the situation I described. That's going to need a little thought on how to fix, unfortunately.

**Comment by bjornsallarp** [comment]
Everyone in my team has the exact same problem. It would be really awesome if this could be solved or if Resharper By Jetbrains could add a context-menu item to scan all files that mimic the original plugin.

**Comment by KJee85** [comment]
Any updates on this issue? I'm still seeing it with 

StyleCop.MSBuild Nuget: 4.7.54.0
ReSharper: 2016.2.2
StyleCop by JetBrains: 2016.2.1

I almost got around it by adding StyleCop.dll from nuget package to GAC but this actually caused StyleCop in general not to actually scan on build even with addin uninstalled.

**Comment by AjayJS** [comment]
Hi,

I am also facing the same issue.

Regards,
Ajay.K

**Comment by SveinungFjaer** [comment]
Any news on this issue?

**Comment by ThielHater** [comment]
I came from #123 and have the same problem as @GeneralSan. The only solution so far is to delete all "yworks*.dll" files from "%localappdata%\JetBrains\Installations\ReSharperPlatformVs15_8617f09a", of course this is not proper as yWorks as a diagram component which is part of ReSharper. This error happens only when StyleCop.ReSharper is installed but I can't spare it.

**Comment by matkoch** [comment]
This should be adressed by #167. Let's wait for @csdahlberg review.

**Comment by ThielHater** [comment]
In the meantime I found out that the error happens in StyleCopCore.LoadAddins(), which is called by StyleCopCore.Initialize(), having the parameter "loadFromDefaultPath" set to "true". I don't know if the pull request of @matkoch fixes this error, because I have problems compiling the Visual Studio extension, but I guess it does.

**Comment by daniel-cohen** [comment]
@ThielHater Thanks ! renaming "yWorks.yFilesWPF.Viewer.dll" seems to be a work around.
