### ISSUE TITLE
StyleCop Violation SA1210 not displayed in Visual Studio CodeFiles

### ISSUE THREAD

**Issue by GuidoLeibbrand** [StyleCop/StyleCop#53]
Hi,

we use :
* VS2015, Update 3
* JetBrains ReSharper Ultimate 2016.1.2    Build 105.0.20160522.80219
* ReSharper Extension: StyleCop by JetBrains 2016.1.0

The violation SA1210 (Using directives must be sorted alphabetically by the namespaces) not displayed in the visual studio code files. 

Only a full cleanup sort the using directives correctly.

How can i reactivate the violation and the resharper quick-fix (Alt+Enter)?

Thank you

**Comment by citizenmatt** [comment]
It is likely that you've changed the severity of the warning. If you've done this in ReSharper, go to Options &rarr; Inspection Severity and search for "1210". You should see the "SA1210: Using Directives Must Be Ordered Alphabetically By Namespace" item - check to see if the associated drop down is set to "Warning".

If you've disabled it via settings, take a look in the Settings.StyleCop files for your project/soltion.
