### ISSUE TITLE
Please add 2016.2 support

### ISSUE THREAD

**Issue by dmitriyse** [StyleCop/StyleCop#55]

**Comment by dmitriyse** [comment]
Termprarly we can use my build of Plugin based on 2016.2 EAP 8

[StyleCop.StyleCop.2016.2.0-Alpha-EAP8.nupkg.zip](https://github.com/StyleCop/StyleCop/files/367915/StyleCop.StyleCop.2016.2.0-Alpha-EAP8.nupkg.zip)
It have bugs but usable with StyleCop analyzers.

**Comment by mvonballmo** [comment]
+1

**Comment by DevHim** [comment]
+1

**Comment by citizenmatt** [comment]
Working on this right now. Should be later today.

**Comment by devlights** [comment]
+1

**Comment by mvonballmo** [comment]
Hi, @citizenmatt: do you have a revised estimate fo when this issue might be completed? I'm in charge of managing upgrades for my company and I've been holding off the move from 10.0.2 until the StyleCop plugin is available for 2016.2. If it's going to be a day or so, I can fend off the other developers; if it's a couple more weeks, I'll have to let them upgrade without it. Thanks for your help!

**Comment by pflugs30** [comment]
Thank you, @citizenmatt!  We appreciate the help.

**Comment by citizenmatt** [comment]
No worries! If anyone's looking for it, it's now available on the Extension Manager.

**Comment by mvonballmo** [comment]
Hooray! Thank you very much. Installed and working very nicely in 2016.2.
