### ISSUE TITLE
SA1600 Ignore Privates - option missing?

### ISSUE THREAD

**Issue by scrockford** [StyleCop/StyleCop#56]
With StyleCop 4.7 the documentation rules could be set to ignore members based on access modifiers.

Is there a way to do this in StyleCop by JetBrains 2016.1.0?  Here is a picture of the option I am referring to. 

Thank You

![stylecop settings](https://cloud.githubusercontent.com/assets/20545764/16966490/cacb9b34-4dd2-11e6-8df5-75a9e1006e71.png)

**Comment by mvonballmo** [comment]
I'm also interested in knowing how to adjust documentation requirements for different visibilities. I have two solutions, one that warns about missing documentation for private members and one that does not. I can't for the life of me figure out which setting controls this feature.

**Comment by citizenmatt** [comment]
The ReSharper plugin should recognise the standard settings, so you can either directly edit the settings.stylecop file, or install style cop from codeplex and use the settings editor (the ReSharper plugin doesn't include the settings editor).
