### ISSUE TITLE
Custom rules not working with Resharper 2016.1.2

### ISSUE THREAD

**Issue by seran77** [StyleCop/StyleCop#58]
We have some custom stylecop rules, which are working fine in the combination VS 2015 Update 3 (latest version), Stylecop 4.7.49 and ReSharper 9.2 with the extension StyleCop for ReSharper 9.2.

When I update to ReSharper 2016.1.2 and the StyleCop by JetBrains extension the normal Stylecop rules are shown, but our custom rules are not. Any clue what the problem could be?

**Comment by mvonballmo** [comment]
I'm using the 2016.2 build released on August 18th and I don't see the StyleCop by JetBrains extension in the Extension Manager. Could you please let me know how you managed to install it? I'd like to use this extension with 2016.2 as well.

**Comment by seran77** [comment]
Hi! We got it to work with 2016.1.2. The trick was to add the dll with our custom rules as stylecop plugin.

![stylecop](https://cloud.githubusercontent.com/assets/21055985/17923493/b6e1c48a-69e4-11e6-9f6b-9cb6424e01a0.png)

But beware that it only works if you save this configuration to 'This computer' not to a project or team.

I didn't get it to work with 2016.2, because the stylecop extension hasn't been updated yet.

**Comment by citizenmatt** [comment]
I haven't updated the 2016.2 extension yet. I'm working on it now. I'm going to close this for now.
