### ISSUE TITLE
StyleCop for Resharper is failing to load in 2016.1

### ISSUE THREAD

**Issue by rsking** [StyleCop/StyleCop#59]
When loading Visual Studio, I'm seeing an error in the ReSharper Log

`Class StyleCop.ReSharper.QuickFixes.Framework.SuppressStyleCopQuickFix marked with attribute JetBrains.ReSharper.Feature.Services.QuickFixes.QuickFixAttribute should have at least one public constructor with one parameter of type derived from JetBrains.ReSharper.Feature.Services.Daemon.IHighlighting`

Which is causing the extension to fail to load, so no highlighting is observed at all.

**Comment by citizenmatt** [comment]
What version of the extension do you have installed?

**Comment by citizenmatt** [comment]
OK, I'm seeing the same error. However, it seems to be ignored, and the normal highlights are still included. I'll work on a fix.
