### ISSUE TITLE
Disabling rules with comments

### ISSUE THREAD

**Issue by ChrisReddickClarity** [StyleCop/StyleCop#60]
Is StyleCop as the ReSharper extension supposed to support the disable and restore comments? When I try using them they seem to have no effect.

**Comment by citizenmatt** [comment]
I'm not sure to be honest. Could you give an example of the comments you're using, please?

**Comment by ChrisReddickClarity** [comment]
Sorry, this email isn't checked very often.

The rule as disabled looks like 
// Resharper disable once SA1506.something
When you use the disable once with comment action

**Comment by citizenmatt** [comment]
Yep. Figured it out :)

Latest version in the extension manager fixes this, although I'm a little wary - ReSharper will ignore the warning with the comment, but a command line StyleCop won't. But there's no way to have a configurable wanting (so you can change the setting to Suggestion or Hint) without also having the comment quick fixes appear in <kbd>Alt</kbd>+<kbd>Enter</kbd>.
