### ISSUE TITLE
StyleCop by Jetbrains missing from extension package feed

### ISSUE THREAD

**Issue by CrispinParker** [StyleCop/StyleCop#76]
I expect it's me but...

I'm not seeing the StyleCop by JetBrains plugin in the R# Extensions NuGet feed. Currently using feed source:

https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v6.0/Packages

And don't see it in the list.

**Comment by citizenmatt** [comment]
I can see it listed correctly - are you still using ReSharper 2016.2?

**Comment by CrispinParker** [comment]
Thanks for taking a look. I thought it must be a "me only" issue or every one else would be shouting.

I am using R# 2016.2.**2** (built September 13). Is SC only available for 2016.2?

If I pull the package feed (indicated in my original post) StyleCop isn't listed. In fact the word "Style" isn't present anywhere in the response stream.

**Comment by citizenmatt** [comment]
No, I was using 2016.2.2 as well. You can try and capture the response via Fiddler, and it should be in there.

**Comment by CrispinParker** [comment]
Manged to get to the bottom of my issue.

The StyleCop plugin was not listed because I already had it installed. Apparently, the file that controls the list of "installed" packages had become corrupted. 

Re-installing R# has fixed the issue.
