### ISSUE TITLE
False positive SA1126

### ISSUE THREAD

**Issue by msmolka** [StyleCop/StyleCop#77]
Hello
there is incorrectly reported rule SA1126 where nameof is used as action name. Parameter is method name.
e.g.
this.RedirectToAction(nameof(VerifyPhoneNumber))

UPDATE
Please ignore. In fact I can use this for nameof

**Comment by msmolka** [comment]
With C# 7 and inline out variables this one is still active.

**Comment by SanjayGuntur** [comment]
@msmolka , with the latest extension, are you still seeing this issue? If not, can you help close the ticket?

**Comment by msmolka** [comment]
Looks on in 2017.1.1
