### ISSUE TITLE
StyleCop.Resharper 2016.3 not working

### ISSUE THREAD

**Issue by msmolka** [StyleCop/StyleCop#78]
I've updated Resharper to version 2016.3 and plugin to 2016.3. However even if plugin is installed it doesn't seem to work. 
E.g. not inserting comments and headers. I've checked options. 
I've uninstalled plugin couple times.
Repaired Resharper. 

Plugin is loaded, because I can see it in Options. However doing nothing.

**Comment by citizenmatt** [comment]
OK, it's good that you can see it in the options page. Is the "analyse as you type" checkbox enabled?

What Visual Studio version are you using? Do you have StyleCopAnalysers added?

**Comment by msmolka** [comment]
Yes, I have it checked.
Visual Studio 2015.
I've tried both projects with added analysers and one without. Neither one is working.

**Comment by citizenmatt** [comment]
Is it just inserting code that fails? Are the warnings working?

**Comment by msmolka** [comment]
I think nothing is working. Just checked couple project which previously informed about lack of documentation wrong order etc. Now nothing is reported.

**Comment by Jan-Olof** [comment]
I seem to be having the same problem after updating to 2016.3. No warnings are working either. (I have Visual Studio 2015.)

**Comment by citizenmatt** [comment]
Do your files have a header? Can you try adding a comment to the top of the file, please? Does everything start working again? It seems to be throwing an exception if the header is missing, which seems to be new behaviour.

**Comment by Jan-Olof** [comment]
Yes it starts working again if I add a comment at the top of a file.

**Comment by citizenmatt** [comment]
Brilliant. I'll get this fixed and push a new version ASAP.

**Comment by citizenmatt** [comment]
Please update!

**Comment by Jan-Olof** [comment]
Thanks for the quick fix!

**Comment by msmolka** [comment]
Working thank you
