### ISSUE TITLE
StyleCop VS Extension and StyleCop for MSBuild use different global settings files

### ISSUE THREAD

**Issue by Mazeppa0** [StyleCop/StyleCop#81]
I am trying to configure a system using StyleCop that works for both development and the build machine. I want to collect all the rule modifications and put them in a single place so I don't have to modify every project we create. The documentation, without being very specific, stated that the location of the global Settings.StyleCop would be where StyleCop.dll was located.

So I installed the StyleCop VS Extension. I put my "global" mods into the Settings.StyleCop located at \Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\rtq5peqy.bch\Settings.StyleCop. I could see my changes when I ran the StyleCop settings dialog in VS or when I ran StyleCop from VS.

Then I hooked up the "MSBuild integration" as suggested by the documentation. When building the solution with MSBuild, StyleCop ran, but it did not see any of my global changes until I added them to the Settings.StyleCop located at \Program Files (x86)\StyleCop 4.7.

So just for grins, I backed out my "MSBuild" integration and installed the NuGet package StyleCop.MSBuild. With this configuration, I can't find **any** location where I can enter my global changes and have MSBuild pick them up. Running StyleCop from VS was unaffected (it still worked correctly).

Wouldn't it be nice if there were only 1 location for the global settings for all ways of running StyleCop?

**Comment by Mazeppa0** [comment]
I found somewhat of a workaround for this issue. Assuming all your code projects share a common parent directory, you can place a Settings.StyleCop file in this common directory and both Visual Studio and MSBuild runs of StyleCop will pick up the modifications.

**Comment by SanjayGuntur** [comment]
@Mazeppa0 , if your issue is resolved, can you help close this ticket?

**Comment by Mazeppa0** [comment]
The workaround is OK. The only drawback is that you have to have a copy or your global Settings.StyleCop file in every repository.
