### ISSUE TITLE
C# documentation rule may fail to load XML documentation in case-sensitive file systems

### ISSUE THREAD

**Issue by peteroupc** [StyleCop/StyleCop#84]
If all the following is true, the rule will fail to load an XML documentation file even if it exists:

- The path of the XML file (including any of its directories) includes any lower-case letters.
- The file system used to store the XML file is case-sensitive.

This is because the rule converts the file path to upper case and tries to load the XML based on that path, rather than using the original file path to do so (see the LoadIncludedDocumentationFile method in DocumentationRules.cs).

(I [previously posted](https://stylecop.codeplex.com/workitem/7755) this on CodePlex, but I learned that I may have better chances of this issue being addressed if I post here instead.)

**Comment by SanjayGuntur** [comment]
Noted, will take a look a look.
If you already know the where the bug is, you can also send a pull request for the fix.
