### ISSUE TITLE
Installation .vsix package

### ISSUE THREAD

**Issue by rorsulak** [StyleCop/StyleCop#90]
When installing StyleCop vsix package by double clicking on file, StyleCop menu items are not visible, but
extension is visible in installed extensions list.
As workaround running command `devenv /updateconfiguration` after installation helped.

Probably in extension.vsixmanifest is missing something like `<Asset Type="Microsoft.VisualStudio.VsPackage" Path="|%CurrentProject%;PkgdefProjectOutputGroup|" />`

**Comment by ImLp** [comment]
Can confirm that this indeed is what I had to do to get it to show up on the menus.

**Comment by SanjayGuntur** [comment]
@rorsulak,  while is did see this issue once in VS 2017 preview release, I cannot repro this issue anymore.
If this is not a problem anymore, can you help close this ticket?

**Comment by rorsulak** [comment]
@SanjayGuntur, I checked it in VS 2017 Enterprise and this issue did not occur.
But I rechecked it in VS 2013 Premium and VS 2015 Enterprise and I was able to reproduce this issue for both versions.

**Comment by rorsulak** [comment]
@SanjayGuntur , I checked it (version 5.0.6419.0) again in VS 2015 Enterprise and this issue did not occur, so it can be closed.
