### ISSUE TITLE
Plugin for R# 2017.1?

### ISSUE THREAD

**Issue by cmeeren** [StyleCop/StyleCop#93]
Will StyleCop be made available for ReSharper 2017.1?

**Comment by DanubeRS** [comment]
Unsure if this relates to #95 ?

**Comment by cmeeren** [comment]
Yes, it's the same.

**Comment by dmitriyse** [comment]
I created unofficial build. It's works. https://github.com/dmitriyse/StyleCop.ReSharper/releases/tag/2017.1-eap7

**Comment by cmeeren** [comment]
Brilliant, thanks! How to I install it?

**Comment by dmitriyse** [comment]
You need to add local package source:
![image](https://cloud.githubusercontent.com/assets/10322215/24517745/7775c97e-1590-11e7-9c68-433d14744c33.png)
Then perform usual extension installation.

**Comment by dmitriyse** [comment]
Please pay attention it works only on EAP7+.

**Comment by cmeeren** [comment]
Thanks! It install fine, but of course there's no support for the new C# 7 syntax. Guess I'll have to wait for the official release for that.

**Comment by dmitriyse** [comment]
Yes, but C# 7.0 support also can be missed in the official plugin build.
C# 7.0 can be adopted later. But now current EAPs allows to migrate to VS 2017 and perform transition of a code base to new *.csproj 2017 that is also very significant.

**Comment by msmolka** [comment]
Any news?, 2017.1 is now rolled out, I'm waiting for this plugin before update.

**Comment by citizenmatt** [comment]
All updated, now available in the extension manager. Thanks!
