### ISSUE TITLE
Resharper plugin for Visual Studio 2017?

### ISSUE THREAD

**Issue by sepharg** [StyleCop/StyleCop#95]
Hi,

I recently moved to visual studio 2017 and I'm not able to find the plugin in resharper's gallery
What are the plans on releasing an updated plugin for this version of VS?
Thanks,

**Comment by citizenmatt** [comment]
Yes, a new version will be released soon, but probably closer to the RTM date.

**Comment by DanubeRS** [comment]
Assuming you mean RTM 2017.1 for R# (As VS'17 is now in the wild). Looking forward to it :)

**Comment by citizenmatt** [comment]
All updated, should be available in the extension manager.

**Comment by sepharg** [comment]
Thanks!!
